pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }

        stage('Testing') {
            steps {
                sh 'python3 manage.py test' 
            }
        }

        stage('Pushing docker to Container registry'){
            steps {
                sh 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k0i2k3v4' 
                sh 'docker build --build-arg postgres_pass=\${POSTGRES_PASSWORD} -t django-poll-app .' 
                sh 'docker tag django-poll-app:latest public.ecr.aws/k0i2k3v4/django-poll-app:latest' 
                sh 'docker push public.ecr.aws/k0i2k3v4/django-poll-app:latest' 
            }
        }

        stage('Removing built containers'){
            steps{
                sh "docker rmi \$(docker images -q)"
            }
        }
    }

}